### ISSUE TITLE
Context-aware line breaking

### ISSUE THREAD

**Issue by skiwi2** [skiwi2/GithubHookSEChatService#34]
Whenever a line gets split due to being over the maximum chat length limit, we should ideally split the line while keeping the context intact.

This concretely means that you should for example not be able to split on links, and quote blocks should be preserved when splitting quotes.

**Comment by Zomis** [comment]
I believe the best thing to do is to use line breaks as the context for splitting, so to speak. So that no split is done in the middle of a line

**Comment by Vogel612** [comment]
Ticket on JavaBot has been closed as completed. Linebreaks are not given preference over there, mostly since we're not expecting linebreaks :( Feel free to draw inspiration from [our implementation](https://github.com/Vincentyification/JavaBot/blob/master/src/main/java/com/gmail/inverseconduit/utils/PrintUtils.java) ;)

**Comment by Vogel612** [comment]
Since nothing happened here, and this is kinda annoying me, feel free to assign me to this...

I'll take care of this using the PrintUtils class as found in JavaBot's com.gmail.inverseconduit.utils

**Comment by Zomis** [comment]
Thanks for the help, @Vogel612. This has been working very well!
